insert into division (name, burmeseName, type) values ('Ayeyarwady Region', 'ဧရာဝတီတိုင်းဒေသကြီး', 'Region');
insert into division (name, burmeseName, type) values ('Bago Region', 'ပဲခူးတိုင်းဒေသကြီး', 'Region');
insert into division (name, burmeseName, type) values ('Chin State', 'ချင်းပြည်နယ်', 'State');
insert into division (name, burmeseName, type) values ('Kachin State', 'ကချင်ပြည်နယ်', 'State');
insert into division (name, burmeseName, type) values ('Kayah State', 'ကယားပြည်နယ်', 'State');
insert into division (name, burmeseName, type) values ('Kayin State', 'ကရင်ပြည်နယ်', 'State');
insert into division (name, burmeseName, type) values ('Magway Region', 'မကွေးတိုင်းဒေသကြီး', 'Region');
insert into division (name, burmeseName, type) values ('Mandalay Region', 'မန္တလေးတိုင်းဒေသကြီး', 'Region');
insert into division (name, burmeseName, type) values ('Mon State', 'မွန်ပြည်နယ်', 'State');
insert into division (name, burmeseName, type) values ('Naypyidaw Union Territory', 'နေပြည်တော် ပြည်ထောင်စုနယ်မြေ', 'Union Territory');
insert into division (name, burmeseName, type) values ('Rakhine State', 'ရခိုင်ပြည်နယ်', 'State');
insert into division (name, burmeseName, type) values ('Sagaing Region', 'စစ်ကိုင်းတိုင်းဒေသကြီး', 'Region');
insert into division (name, burmeseName, type) values ('Shan State', 'ရှမ်းပြည်နယ်', 'State');
insert into division (name, burmeseName, type) values ('Tanintharyi Region', 'တနင်္သာရီတိုင်းဒေသကြီး', 'Region');
insert into division (name, burmeseName, type) values ('Yangon Region', 'ရန်ကုန်တိုင်းဒေသကြီး', 'Region');